[BUG]: out of license

## Command Line
C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Scripts\pyarmor gen -O C:\code\WeChatBot_WXAUTO_SE\dist\obfuscated C:\code\WeChatBot_WXAUTO_SE\config_editor.py

## Environments
Python 3.12.10
Pyarmor 9.1.7 (trial), 000000, non-profits
Platform windows.aarch64
Native windows.arm64
Home C:\Users\raxcl\.pyarmor

## Traceback
Traceback (most recent call last):
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__main__.py", line 793, in main
    main_entry(sys.argv[1:])
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__main__.py", line 786, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__main__.py", line 248, in cmd_gen
    builder.process(options)
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\generate.py", line 188, in process
    self._obfuscate_scripts()
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\generate.py", line 144, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\core\__init__.py", line 95, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 715, in generate_obfuscated_script
  File "C:\Users\raxcl\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 546, in process
  File "<maker>", line 552, in coserialize
  File "<maker>", line 597, in _build_ast_body
RuntimeError: out of license


